import struct
import random


# FORMAT OF HEADER:
#   Connection ID: rnd generated            
#   Sequence Number: 0 or 1
#   Message Type: REQ, ACK, DATA, or ERR
#   Payload Length: in bytes

MSG_REQUEST = 1
MSG_ACK     = 2
MSG_ERROR   = 3
MSG_DATA    = 4

MSG_TYPES = {
    MSG_REQUEST :   "REQUEST",
    MSG_ACK     :   "ACK",
    MSG_ERROR   :   "ERROR",
    MSG_DATA    :   "DATA"
}

HEADER_FORMAT = "!IBBI"
HEADER_SIZE = struct.calcsize(HEADER_FORMAT)

def get_connection_id() -> int:
    """return: randly generates 4-byte connection id"""
    return random.randint(0, 0xFFFFFFFF)

def get_message_type(msg_type:int):
    """ returns the message type given an int"""
    return MSG_TYPES.get(msg_type, f"UNKNOWN(Ox{msg_type:02x})")
    

def create_packet(connection_id:int, seq_num:int, msg_type:int, payload:bytes)->bytes:
    """Serialize the packet: header + payload

    Args:
        connection_id : ID (generated by client)
        seq_num       : alternating 0/1 for stop-and-wait
        msg_type      : MSG_REQUEST | MSG_DATA | MSG_ACK | MSG_ERROR
        payload       : bytes (either the filename or the chunks of data)

    Returns: 
        bytes:  UDP packet (header + data)
    
    """
    header = struct.pack(
        HEADER_FORMAT,
        connection_id,
        seq_num,
        msg_type,
        len(payload)
    )

    return header + payload


def unpack_packet(data:bytes):
    """Deserialize the header"""
    if len(data) < HEADER_SIZE:
        print(f"Packet is smaller ({len(data)}bytes) than defined header size ({HEADER_SIZE})")
    
    connection_id, seq_num, msg_type, payload_length = struct.unpack(HEADER_FORMAT, data[:HEADER_SIZE])
    
    payload = data[HEADER_SIZE : HEADER_SIZE + payload_length]

    return {
        'connection_id':    connection_id,
        'seq_num':          seq_num,
        'msg_type':         msg_type,
        'payload_length':   payload_length,
        'payload':          payload 
    }
